apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-file-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-file-manager
  template:
    metadata:
      labels:
        app: kube-file-manager
    spec:
      containers:
        - name: kube-file-manager
          image: file-manager-blueprint:v2
          imagePullPolicy: Never
          ports:
            - containerPort: 3001