replicaCount: 2

image:
  repository: kuzinvadym/backend_demo_filemanager
  pullPolicy: IfNotPresent
  tag: sha-1c2bbe5

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

application:
  secretName:
  env:
    NODE_ENV: production
    PORT: "3333"

service:
  type: ClusterIP
  internalPort: 3333
  externalPort: 3333

livenessProbe:
  path: "/api/health"
  initialDelaySeconds: 15
  timeoutSeconds: 5
  scheme: "HTTP"
  probeType: "httpGet"
readinessProbe:
  path: "/api/health"
  initialDelaySeconds: 15
  timeoutSeconds: 3
  scheme: "HTTP"
  probeType: "httpGet"

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 200m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# podDisruptionBudget: {}
podDisruptionBudget:
  enabled: true
  minAvailable: 1
