replicaCount: 2

image:
  repository: kuzinvadym/backend_demo_proxy
  pullPolicy: IfNotPresent
  tag: sha-9b9cd67

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

application:
  secretName:
  env:
    NODE_ENV: production
    WEB_PORT: "3002"

service:
  type: ClusterIP
  internalPort: 3002
  externalPort: 3002

livenessProbe:
  path: "/api/v1//health"
  initialDelaySeconds: 5
  timeoutSeconds: 5
  scheme: "HTTP"
  probeType: "httpGet"
readinessProbe:
  path: "/api/v1/health"
  initialDelaySeconds: 5
  timeoutSeconds: 5
  scheme: "HTTP"
  probeType: "httpGet"

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# podDisruptionBudget: {}
podDisruptionBudget:
  enabled: true
  minAvailable: 1

prometheus:
  metrics: false
